<?php

declare(strict_types=1);

namespace App\Retailing\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\Migrations\Exception\IrreversibleMigration;

/**
 * Converts the remaining legacy SERIAL identifier to PostgreSQL identity
 * while preserving the next generated identifier.
 */
final class Version20260928220500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Convert retail_response.id from SERIAL to GENERATED BY DEFAULT AS IDENTITY.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform,
            'Retailing production schema requires PostgreSQL.',
        );
        $this->abortIf(!$schema->hasTable('retail_response'), 'retail_response table is required before identity normalization.');

        $table = $schema->getTable('retail_response');
        $this->abortIf(!$table->hasColumn('id'), 'retail_response.id is required before identity normalization.');

        $nextId = (int) $this->connection->fetchOne('SELECT COALESCE(MAX(id), 0) + 1 FROM retail_response');
        $this->abortIf($nextId < 1, 'Retail response identity seed must be positive.');

        $this->addSql('ALTER TABLE retail_response ALTER COLUMN id DROP DEFAULT');
        $this->addSql('DROP SEQUENCE IF EXISTS retail_response_id_seq');
        $this->addSql(sprintf(
            'ALTER TABLE retail_response ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %d)',
            $nextId,
        ));
    }

    public function down(Schema $schema): void
    {
        throw new IrreversibleMigration('Retail response identity normalization is intentionally irreversible.');
    }
}
