<?php

declare(strict_types=1);

namespace App\Retailing\Migrations;

use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\Migrations\Exception\IrreversibleMigration;

final class Version20260812223000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adopt or create the Retailing baseline schema and enforce database-level retail invariants';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(!$this->connection->getDatabasePlatform() instanceof PostgreSQLPlatform, 'Retailing production schema requires PostgreSQL.');

        if ($schema->hasTable('retail')) {
            $table = $schema->getTable('retail');
            foreach ([
                'id',
                'kind',
                'owner_vendor_id',
                'category_id',
                'title',
                'description',
                'amount_minor',
                'currency',
                'location',
                'object_code',
                'object_active',
                'object_enabled',
                'object_status',
                'object_created_at',
                'object_modified_at',
                'object_created_by',
                'object_modified_by',
            ] as $column) {
                $this->abortIf(!$table->hasColumn($column), sprintf('Existing retail table is missing required column "%s"; refusing unsafe baseline adoption.', $column));
            }
        } else {
            $this->addSql(<<<'SQL'
CREATE TABLE retail (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    kind VARCHAR(16) NOT NULL,
    owner_vendor_id VARCHAR(64) DEFAULT NULL,
    category_id VARCHAR(64) DEFAULT NULL,
    title VARCHAR(180) NOT NULL,
    description TEXT DEFAULT NULL,
    amount_minor BIGINT DEFAULT NULL,
    currency VARCHAR(3) DEFAULT 'USD' NOT NULL,
    location VARCHAR(255) DEFAULT NULL,
    object_code VARCHAR(190) DEFAULT NULL,
    object_active BOOLEAN DEFAULT TRUE NOT NULL,
    object_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    object_status VARCHAR(64) DEFAULT NULL,
    object_created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    object_modified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    object_created_by VARCHAR(190) DEFAULT NULL,
    object_modified_by VARCHAR(190) DEFAULT NULL,
    PRIMARY KEY(id)
)
SQL);
        }

        $this->addSql('CREATE INDEX IF NOT EXISTS idx_retail_owner_kind ON retail (owner_vendor_id, kind)');
        $this->addSql('CREATE INDEX IF NOT EXISTS idx_retail_category_kind ON retail (category_id, kind)');
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_retail_amount_nonnegative') THEN ALTER TABLE retail ADD CONSTRAINT chk_retail_amount_nonnegative CHECK (amount_minor IS NULL OR amount_minor >= 0); END IF; END $$");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_retail_currency_code') THEN ALTER TABLE retail ADD CONSTRAINT chk_retail_currency_code CHECK (currency ~ '^[A-Z]{3}$'); END IF; END $$");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_retail_kind') THEN ALTER TABLE retail ADD CONSTRAINT chk_retail_kind CHECK (kind IN ('task', 'service', 'goods', 'project')); END IF; END $$");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_retail_publishable_state') THEN ALTER TABLE retail ADD CONSTRAINT chk_retail_publishable_state CHECK (object_status <> 'published' OR (owner_vendor_id IS NOT NULL AND btrim(owner_vendor_id) <> '' AND category_id IS NOT NULL AND btrim(category_id) <> '' AND btrim(title) <> '')); END IF; END $$");
        $this->addSql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_retail_modified_after_created') THEN ALTER TABLE retail ADD CONSTRAINT chk_retail_modified_after_created CHECK (object_modified_at IS NULL OR object_modified_at >= object_created_at); END IF; END $$");
    }

    public function down(Schema $schema): void
    {
        throw new IrreversibleMigration('Retailing baseline adoption is intentionally irreversible; dropping the retail table would destroy production data.');
    }
}
