services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Retailing\Form\RetailType: ~
    App\Retailing\Normalizer\RetailPricingProfileNormalizer: ~

    App\Retailing\EventSubscriber\RetailOwnershipSubscriber:
        tags: ['cruding.mutation_lifecycle_subscriber']

    App\Retailing\Service\Http\Retail\RetailNewService:
        tags: ['cruding.resource_service']

