services:
    App\Retailing\DataFixtures\RetailMarketplaceFixtures:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'doctrine.fixture.orm', group: 'retailing_marketplace' }

    App\Retailing\DataFixtures\RetailCustomerRequestFixtures:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'doctrine.fixture.orm', group: 'retailing_customer_requests' }

    App\Retailing\DataFixtures\RetailResponseFixtures:
        autowire: true
        autoconfigure: true
        tags:
            - { name: 'doctrine.fixture.orm', group: 'retailing_responses' }
