services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Retailing\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/RetailingBundle.php'

    App\Retailing\Controller\Admin\RetailCrudController:
        tags: ['controller.service_arguments']
