services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Retailing\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/RetailingBundle.php'

    App\Retailing\Controller\Admin\RetailCrudController:
        tags: ['controller.service_arguments']

when@dev:
    services:
        App\Retailing\DataFixtures\RetailMarketplaceFixtures:
            tags: ['doctrine.fixture.orm']

when@test:
    services:
        App\Retailing\DataFixtures\RetailMarketplaceFixtures:
            tags: ['doctrine.fixture.orm']
