services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Retailing\Form\Retail\RetailType: ~

    App\Retailing\Subscriber\Retail\RetailOwnershipSubscriber:
        tags: ['cruding.mutation_lifecycle_subscriber']

    App\Retailing\Service\Http\Retail\RetailNewService:
        tags: ['cruding.resource_service']

